import type { NextPage } from "next";
import Head from "next/head";
import axios from "axios";

import { IVideo } from "../types";
import { VideoCard, NoResults } from "../components";

interface IProps {
  videos: IVideo[];
}

const Home = ({ videos }: IProps) => {
  return (
    <div>
      <Head>
        <title>TikTik App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col gap-10 h-full videos">
        {videos?.length > 0 ? (
          videos.map((item: IVideo) => <VideoCard key={item._id} post={item} />)
        ) : (
          <NoResults text="No Videos" />
        )}
      </div>
    </div>
  );
};

export const getServerSideProps = async () => {
  const res = await axios.get(`${process.env.NEXT_PUBLIC_BASE_URL}/api/post`);

  return {
    props: {
      videos: res.data,
    },
  };
};

export default Home;
