import Head from "next/head";
import axios from "axios";

import { IVideo } from "../types";
import { VideoCard, NoResults } from "../components";

interface IProps {
  videos: IVideo[];
}

const Home = ({ videos }: IProps) => {
  return (
    <div>
      <Head>
        <title>TikTik App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col gap-10 h-full videos">
        {videos?.length > 0 ? (
          videos.map((item: IVideo) => <VideoCard key={item._id} post={item} />)
        ) : (
          <NoResults text="No Videos" />
        )}
      </main>
    </div>
  );
};

export const getServerSideProps = async ({
  query: { topic },
}: {
  query: { topic: string };
}) => {
  const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;

  let res = null;

  if (topic) {
    res = await axios.get(`${BASE_URL}/api/discover/${topic}`);
  } else {
    res = await axios.get(`${BASE_URL}/api/post`);
  }

  return {
    props: {
      videos: res.data,
    },
  };
};

export default Home;
